### ISSUE TITLE
Resize images

### ISSUE THREAD

**Issue by lyso** [mvdkwast/obsidian-copy-as-html#16] opened 2023-01-02 23:16 UTC
**Is your feature request related to a problem? Please describe.**
When copy HTML of a note with images, it can convert the image into base64 inside the HTML. This is a great feature! Thanks so much.

But the images are in their raw file image sizes in the output HTML. For example, a png file of size 1920*1080, and in the note it was set display width as 400 (`![[image/path.png|400]]`). In the copied HTML, it is still 1920 wide not 400.

**Describe the solution you'd like**
If it is possible to have the image resized according to the MD setting? like `![[image/path.png|400]]` ?

**Describe alternatives you've considered**
na

**Additional context**
na

**Comment by mvdkwast** [comment] 2023-01-14 01:12
Hi @lyso,

I wasn't aware that this was even possible in Obsidian. Very good suggestion indeed, that would give a lot more control over the resulting size of the base64.

I will look into this.

**Comment by mvdkwast** [comment] 2023-09-13 21:54
This seems to be fixed by the updates to the internal Obsidian markdown renderer.

Feel free to reopen if you can still reproduce the issue.

**Closed by mvdkwast** 2023-09-13 21:54 UTC
Labels: enhancement
